from __future__ import annotations

from typing import Any, Protocol

from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.request_adapter import RequestAdapter


class CollectionRequestBuilder(Protocol):
    """Structural type for Graph SDK request builders that return paged collections.

    WHY THIS EXISTS — DESIGN DECISION SUMMARY
    ==========================================
    The Microsoft Graph Python SDK is generated by kiota. Every resource request
    builder (e.g. `TasksRequestBuilder`, `PlansRequestBuilder`) inherits from
    `kiota_abstractions.base_request_builder.BaseRequestBuilder`, which provides
    only three attributes: `request_adapter`, `url_template`, and `path_parameters`.
    The `.get()` method is NOT part of `BaseRequestBuilder` — it is generated
    per-resource on each concrete subclass.

    APPROACHES CONSIDERED (and why each was rejected):

    1. Type as `BaseRequestBuilder` directly
       → Rejected: produces "unresolved attribute .get()" errors in type checkers
         because `.get()` is not declared on the base class.

    2. Abstract subclass of `kiota_abstractions.base_request_builder.BaseRequestBuilder`
       with an abstract `.get()` method
       → Rejected: generated builders inherit `BaseRequestBuilder` directly (not
         our subclass), so `issubclass(TasksRequestBuilder, OurSubclass)` returns
         `False` and type-checker assignments fail. You cannot retrofit an
         inheritance hierarchy onto code-generated classes.
         Verified via: `TasksRequestBuilder.__mro__` → [TasksRequestBuilder,
         BaseRequestBuilder, object].

    3. `Protocol(BaseRequestBuilder)` — Protocol inheriting the non-Protocol class
       → Rejected: behavior is version-dependent. Python 3.12+ raises `TypeError`
         at class definition time; earlier versions (3.8–3.11) may not raise
         immediately but the resulting class loses structural subtyping guarantees
         — mypy and pyright both reject it regardless. The conclusion is the same
         across all versions: it does not work.

    4. Type as `Any`
       → Rejected: silences errors but abandons all type safety.

    5. Protocol (current approach) ✓
       → Correct: Python Protocols (PEP 544) use structural subtyping — a class
         satisfies a Protocol if it has the required attributes/methods, regardless
         of inheritance. Since all generated collection builders have both
         `request_adapter` (from BaseRequestBuilder) and an async `.get()`, they
         satisfy this Protocol without modification.
         Docs: https://peps.python.org/pep-0544/

    WHY `.get()` CANNOT BE SKIPPED:
    `msgraph_core.tasks.page_iterator.PageIterator.__init__` requires a pre-fetched
    first-page response object — there is no constructor that accepts a request
    builder and fetches lazily. Calling `.get()` on the concrete builder first is
    the documented pattern for all Graph SDK languages.
    Docs: https://learn.microsoft.com/en-us/graph/sdks/paging

    EXTENSION POINT:
    This Protocol is the right place to add additional verb support if needed.
    For example, if `paginate` ever needs to support `post()` for delta queries,
    add `async def post(...)` here rather than widening the type elsewhere.

    WHAT `BaseRequestBuilder` IS FOR (context):
    It is kiota's internal base for code-generated clients. It stores routing state
    (`url_template`, `path_parameters`) and the injected `RequestAdapter` (which
    owns auth, serialisation, and retries). It enables fluent navigation chains
    (e.g. `.planner.tasks.by_planner_task_id(id).details`). SDK consumers never
    instantiate or subclass it directly.
    Source: kiota_abstractions.base_request_builder.BaseRequestBuilder
    """

    request_adapter: RequestAdapter

    async def get(self, request_configuration: RequestConfiguration | None = None) -> Any: ...
